name: Pipeline Imobiliaria

on:
  push:
  pull_request:

jobs:
  aluguel:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Mostrar arquivos
        run: ls -R

      - name: Executar sistema
        run: python imovel.py

      - name: Executar testes
        run: python teste_imovel.py

      - name: Finalizar pipeline
        run: echo "Sistema validado com sucesso"
